# Generated by Django 4.0.4 on 2023-06-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Window',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('url', models.CharField(default='', max_length=100)),
                ('elementId', models.CharField(default='', max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('top', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='WindowModel',
        ),
    ]
