# Generated by Django 4.0.4 on 2023-06-23 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snowball_main', '0002_window_delete_windowmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ['name']},
        ),
    ]
