# Generated by Django 4.0.4 on 2023-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball_main', '0003_alter_window_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='window',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
