# Generated by Django 4.0.4 on 2023-07-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snowball_main', '0005_remove_window_left_remove_window_top_window_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='window',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
