# Generated by Django 4.0.4 on 2023-06-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=255)),
                ('technology', models.CharField(choices=[('SW', 'SwiftUI'), ('RE', 'React'), ('JP', 'Jetpack')], default='SW', max_length=2)),
                ('content', models.TextField()),
            ],
        ),
    ]
