# Generated by Django 4.0.4 on 2023-06-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snowball_passkey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnowballAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='The user-friendly name for this key.', max_length=200)),
                ('credential_id', models.CharField(max_length=300, unique=True)),
                ('public_key', models.CharField(max_length=500)),
                ('sign_count', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('last_used_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'auth data',
            },
        ),
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
